theme: jekyll-theme-architect
title: Ion Trap/ Jun_Wang
tagline: Jun_Wang @ TIQC Lab
owner: congzlwag
plugins:
  - jekyll-sitemap


lsi: false
safe: true
source: [https://github.com/iontrapnet/Jun_Wang]
incremental: false
highlighter: rouge
gist:
 noscript: false
kramdown:
 math_engine: mathjax
 syntax_highlighter: rouge