# theme: jekyll-theme-architect
theme: 
title: Ion Trap/ Jun_Wang
description: Archive of Jun_Wang @ TIQC Lab
homurl: http://www.iontrap.net/Jun_Wang
#link: http://www.iontrap.net
#copyright: '&copy;&nbsp;<a href="http://www.iontrap.net">IonTrap.Net</a>'

# permalink: pretty
# markdown: kramdown
# kramdown:
#     input: GFM
#     math_engine: mathjax
#     auto_ids: true
#     syntax_highlighter: rouge
#     syntax_highlighter_opts:
#         # Use existing pygments syntax highlighting css
#         css_class: 'highlight'
#markdown: redcarpet
#redcarpet:
#    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "highlight", "quote", "footnotes", "strikethrough", "with_toc_data"]
# gems:
#   - jekyll-sitemap
exclude: [README.md]